Update index.html
GhostM244/potionfy pull request #3
Opened 2022-09-19 23:12 UTC by ClebioMedeiros1

Aqui estão as minhas modificações no site.

2022-09-19 23:18 UTC, GhostM244 commented on index.html
> +      <h1>Sejam bem Vindos a nossa loja virtual! Boas Compras!</h1>
Tem como trocar esse "Boas compras" por algo mais chamativo? Ah, e tenta por o "Sejam bem vindos a nossa loja virtual" em vermelho, por favor!

2022-09-21 23:38 UTC, GhostM244 requested changes
Então altera aí 👯

2022-09-22 00:02 UTC, merged

2022-09-22 00:03 UTC, ClebioMedeiros1 commented
Já foi feita a alteração.

2022-09-22 00:17 UTC, GhostM244 commented
Cometi um erro  e vi que a alteração estava perfeita, vlw